// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeLoginPassword(arg1, arg2) {
  return window['go']['app']['App']['ChangeLoginPassword'](arg1, arg2);
}

export function CheckAccessibilityPermission() {
  return window['go']['app']['App']['CheckAccessibilityPermission']();
}

export function CheckAndRepairCorruptedAccounts() {
  return window['go']['app']['App']['CheckAndRepairCorruptedAccounts']();
}

export function CheckRecentVaultStatus() {
  return window['go']['app']['App']['CheckRecentVaultStatus']();
}

export function CheckVaultExists(arg1) {
  return window['go']['app']['App']['CheckVaultExists'](arg1);
}

export function ClearUsernameHistory() {
  return window['go']['app']['App']['ClearUsernameHistory']();
}

export function CloseVault() {
  return window['go']['app']['App']['CloseVault']();
}

export function CopyAccountNotes(arg1) {
  return window['go']['app']['App']['CopyAccountNotes'](arg1);
}

export function CopyAccountPassword(arg1) {
  return window['go']['app']['App']['CopyAccountPassword'](arg1);
}

export function CopyAccountUsername(arg1) {
  return window['go']['app']['App']['CopyAccountUsername'](arg1);
}

export function CopyAccountUsernameAndPassword(arg1) {
  return window['go']['app']['App']['CopyAccountUsernameAndPassword'](arg1);
}

export function CreateAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CreateAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateCustomPasswordRule(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateCustomPasswordRule'](arg1, arg2, arg3);
}

export function CreateGeneralPasswordRule(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateGeneralPasswordRule'](arg1, arg2, arg3);
}

export function CreateGroup(arg1) {
  return window['go']['app']['App']['CreateGroup'](arg1);
}

export function CreateType(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateType'](arg1, arg2, arg3);
}

export function CreateVault(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateVault'](arg1, arg2, arg3);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['app']['App']['DeleteGroup'](arg1);
}

export function DeletePasswordRule(arg1) {
  return window['go']['app']['App']['DeletePasswordRule'](arg1);
}

export function DeleteType(arg1) {
  return window['go']['app']['App']['DeleteType'](arg1);
}

export function ExportVault(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['ExportVault'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ForceInitializeDefaultPasswordRules(arg1) {
  return window['go']['app']['App']['ForceInitializeDefaultPasswordRules'](arg1);
}

export function GeneratePasswordByCustomConfig(arg1) {
  return window['go']['app']['App']['GeneratePasswordByCustomConfig'](arg1);
}

export function GeneratePasswordByGeneralConfig(arg1) {
  return window['go']['app']['App']['GeneratePasswordByGeneralConfig'](arg1);
}

export function GeneratePasswordByRule(arg1) {
  return window['go']['app']['App']['GeneratePasswordByRule'](arg1);
}

export function GetAccountByID(arg1) {
  return window['go']['app']['App']['GetAccountByID'](arg1);
}

export function GetAccountCredentials(arg1) {
  return window['go']['app']['App']['GetAccountCredentials'](arg1);
}

export function GetAccountDetail(arg1) {
  return window['go']['app']['App']['GetAccountDetail'](arg1);
}

export function GetAccountNotes(arg1) {
  return window['go']['app']['App']['GetAccountNotes'](arg1);
}

export function GetAccountPassword(arg1) {
  return window['go']['app']['App']['GetAccountPassword'](arg1);
}

export function GetAccountRaw(arg1) {
  return window['go']['app']['App']['GetAccountRaw'](arg1);
}

export function GetAccountsByConditions(arg1) {
  return window['go']['app']['App']['GetAccountsByConditions'](arg1);
}

export function GetAccountsByGroup(arg1) {
  return window['go']['app']['App']['GetAccountsByGroup'](arg1);
}

export function GetAccountsByTab(arg1) {
  return window['go']['app']['App']['GetAccountsByTab'](arg1);
}

export function GetAllAccounts() {
  return window['go']['app']['App']['GetAllAccounts']();
}

export function GetAllPasswordRules() {
  return window['go']['app']['App']['GetAllPasswordRules']();
}

export function GetAllTypes() {
  return window['go']['app']['App']['GetAllTypes']();
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetChangeLog() {
  return window['go']['app']['App']['GetChangeLog']();
}

export function GetCurrentPassword() {
  return window['go']['app']['App']['GetCurrentPassword']();
}

export function GetCurrentVaultPath() {
  return window['go']['app']['App']['GetCurrentVaultPath']();
}

export function GetDefaultPasswordRule() {
  return window['go']['app']['App']['GetDefaultPasswordRule']();
}

export function GetGroups() {
  return window['go']['app']['App']['GetGroups']();
}

export function GetHotkeyConfig() {
  return window['go']['app']['App']['GetHotkeyConfig']();
}

export function GetLastWindowInfo() {
  return window['go']['app']['App']['GetLastWindowInfo']();
}

export function GetLockConfig() {
  return window['go']['app']['App']['GetLockConfig']();
}

export function GetLogConfig() {
  return window['go']['app']['App']['GetLogConfig']();
}

export function GetPasswordRuleByID(arg1) {
  return window['go']['app']['App']['GetPasswordRuleByID'](arg1);
}

export function GetPreviousFocusedAppName() {
  return window['go']['app']['App']['GetPreviousFocusedAppName']();
}

export function GetRecentVaults() {
  return window['go']['app']['App']['GetRecentVaults']();
}

export function GetTimerStatus() {
  return window['go']['app']['App']['GetTimerStatus']();
}

export function GetTypesByGroup(arg1) {
  return window['go']['app']['App']['GetTypesByGroup'](arg1);
}

export function GetUsageDays() {
  return window['go']['app']['App']['GetUsageDays']();
}

export function GetUsernameHistory(arg1) {
  return window['go']['app']['App']['GetUsernameHistory'](arg1);
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function ImportVault(arg1, arg2) {
  return window['go']['app']['App']['ImportVault'](arg1, arg2);
}

export function InsertTypeAfter(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['InsertTypeAfter'](arg1, arg2, arg3, arg4);
}

export function IsLockTriggered() {
  return window['go']['app']['App']['IsLockTriggered']();
}

export function IsVaultOpened() {
  return window['go']['app']['App']['IsVaultOpened']();
}

export function IsWindowVisible() {
  return window['go']['app']['App']['IsWindowVisible']();
}

export function MoveGroupLeft(arg1) {
  return window['go']['app']['App']['MoveGroupLeft'](arg1);
}

export function MoveGroupRight(arg1) {
  return window['go']['app']['App']['MoveGroupRight'](arg1);
}

export function MoveTypeDown(arg1) {
  return window['go']['app']['App']['MoveTypeDown'](arg1);
}

export function MoveTypeUp(arg1) {
  return window['go']['app']['App']['MoveTypeUp'](arg1);
}

export function OnWindowBlur() {
  return window['go']['app']['App']['OnWindowBlur']();
}

export function OnWindowFocus() {
  return window['go']['app']['App']['OnWindowFocus']();
}

export function OnWindowMinimize() {
  return window['go']['app']['App']['OnWindowMinimize']();
}

export function OpenVault(arg1, arg2) {
  return window['go']['app']['App']['OpenVault'](arg1, arg2);
}

export function OpenVaultDirectory() {
  return window['go']['app']['App']['OpenVaultDirectory']();
}

export function RecordLastWindow() {
  return window['go']['app']['App']['RecordLastWindow']();
}

export function RenameGroup(arg1, arg2) {
  return window['go']['app']['App']['RenameGroup'](arg1, arg2);
}

export function SaveUsernameToHistory(arg1, arg2) {
  return window['go']['app']['App']['SaveUsernameToHistory'](arg1, arg2);
}

export function SearchAccounts(arg1) {
  return window['go']['app']['App']['SearchAccounts'](arg1);
}

export function SelectExportPath() {
  return window['go']['app']['App']['SelectExportPath']();
}

export function SelectImportFile() {
  return window['go']['app']['App']['SelectImportFile']();
}

export function SelectVaultFile() {
  return window['go']['app']['App']['SelectVaultFile']();
}

export function SetAppConfig(arg1) {
  return window['go']['app']['App']['SetAppConfig'](arg1);
}

export function SetHotkeyConfig(arg1) {
  return window['go']['app']['App']['SetHotkeyConfig'](arg1);
}

export function SetLockConfig(arg1) {
  return window['go']['app']['App']['SetLockConfig'](arg1);
}

export function SetLogConfig(arg1) {
  return window['go']['app']['App']['SetLogConfig'](arg1);
}

export function SetPasswordRuleAsDefault(arg1, arg2) {
  return window['go']['app']['App']['SetPasswordRuleAsDefault'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function SimulatePassword(arg1) {
  return window['go']['app']['App']['SimulatePassword'](arg1);
}

export function SimulateUsername(arg1) {
  return window['go']['app']['App']['SimulateUsername'](arg1);
}

export function SimulateUsernameAndPassword(arg1) {
  return window['go']['app']['App']['SimulateUsernameAndPassword'](arg1);
}

export function StorePreviousFocusedApp() {
  return window['go']['app']['App']['StorePreviousFocusedApp']();
}

export function SwitchToLastWindow() {
  return window['go']['app']['App']['SwitchToLastWindow']();
}

export function SwitchToPasswordManager() {
  return window['go']['app']['App']['SwitchToPasswordManager']();
}

export function TestToggleWindow() {
  return window['go']['app']['App']['TestToggleWindow']();
}

export function ToggleWindow() {
  return window['go']['app']['App']['ToggleWindow']();
}

export function TriggerLock() {
  return window['go']['app']['App']['TriggerLock']();
}

export function UpdateAccount(arg1) {
  return window['go']['app']['App']['UpdateAccount'](arg1);
}

export function UpdateAccountGroup(arg1, arg2) {
  return window['go']['app']['App']['UpdateAccountGroup'](arg1, arg2);
}

export function UpdateAccountUsage(arg1) {
  return window['go']['app']['App']['UpdateAccountUsage'](arg1);
}

export function UpdateAppUsage() {
  return window['go']['app']['App']['UpdateAppUsage']();
}

export function UpdateCustomPasswordRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateCustomPasswordRule'](arg1, arg2, arg3, arg4);
}

export function UpdateGeneralPasswordRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateGeneralPasswordRule'](arg1, arg2, arg3, arg4);
}

export function UpdateGroupSortOrder(arg1, arg2) {
  return window['go']['app']['App']['UpdateGroupSortOrder'](arg1, arg2);
}

export function UpdateType(arg1) {
  return window['go']['app']['App']['UpdateType'](arg1);
}

export function UpdateTypeSortOrder(arg1, arg2) {
  return window['go']['app']['App']['UpdateTypeSortOrder'](arg1, arg2);
}

export function UpdateUserActivity() {
  return window['go']['app']['App']['UpdateUserActivity']();
}

export function VerifyOldPassword(arg1) {
  return window['go']['app']['App']['VerifyOldPassword'](arg1);
}
